

CREATE TABLE "AVA_WM_SRP1"(
	"DocEntry" int NOT NULL,
	"LineId" int NOT NULL,
	"Object" varchar(30) NULL,
	"LineStatus" varchar(1) NULL,
	"Ref1" nvarchar(100) NULL,
	"Ref2" nvarchar(200) NULL,
	"BaseType" nvarchar(30) NOT NULL,
	"BaseEntry" int NOT NULL,
	"BaseLine" int NOT NULL,
	"Project" nvarchar(8) NULL,
	"OcrCode1" nvarchar(8) NULL,
	"OcrCode2" nvarchar(8) NULL,
	"OcrCode3" nvarchar(8) NULL,
	"OcrCode4" nvarchar(8) NULL,
	"OcrCode5" nvarchar(8) NULL,
	"BSType" nvarchar(30) NULL,
	"BSEntry" int NULL,
	"BSLine" int NULL,
	"TargetType" nvarchar(30) NULL,
	"TargetEntry" int NULL,
	"TargetLine" int NULL,
	"ItemCode" nvarchar(20) NOT NULL,
	"ItemName" nvarchar(200) NULL,
	"Quantity" numeric(19, 6) NOT NULL,
	"Uom" nvarchar(8) NULL,
	"ManSerNum" nvarchar(1) NULL,
	"ManBtchNum" nvarchar(1) NULL,
	"ManServiceNum" nvarchar(1) NULL,
	"Price" numeric(19, 6) NULL,
	"Currency" nvarchar(8) NULL,
	"Rate" numeric(19, 6) NULL,
	"LineTotal" numeric(19, 6) NULL,
	"FromWH" nvarchar(8) NULL,
	"FromLC" nvarchar(60) NULL,
	"ToWH" nvarchar(8) NULL,
	"ToLC" nvarchar(60) NULL,
	"BatchNum" nvarchar(30) NULL,
	"SerialNum" nvarchar(30) NULL,
	"BarCode1" nvarchar(60) NULL,
	"BarCode2" nvarchar(60) NULL,
	"BarCode3" nvarchar(60) NULL,
	"BarCode4" nvarchar(60) NULL
);
CREATE INDEX KAVA_WM_SRP1 ON AVA_WM_SRP1("DocEntry","LineId");

